class Strings {
  Strings._();

  static const String buttonCerrarSesion = "Cerrar sesión";
  static const String buttonTema = "Tema";
  static const String buttonPerfil = "Perfil";
  static const String labelGrupo = "Crear grupo";
  static const String labelEditarGrupo = "Editar grupo";
  static const String msgAdmin = "Solo el administrador del grupo puede editarlo";
  static const String buttonReturnInicio = "Volver a inicio";
  static const String buttonDetailGrupo = "Detalle del grupo";
  static const String labelNameGrupo = "Nombre de grupo";
  static const String msgNameGrupo = "Ingrese el nombre del grupo";
  static const String labelDescGrupo = "Descripción de grupo";
  static const String msgDescGrupo = "Ingrese descripción del grupo (mínimo 10 caracteres)";
  static const String labelBuscar = "Buscar integrantes: ";
  static const String labelProcesando = "Procesando";
  static const String labelCancelar = "Cancelar";
  static const String labelDashboard = "Dashboard";
  static const String labelHorario = "Mi horario";
  static const String labelHorarioJob = "Horas de trabajo";
  static const String labelMisGrupos = "Mis grupos";
  static const String labelDetailGrupo = "Detalles del grupo";
  static const String labelHorarioCalculado = "Horario grupal calculado:";
  static const String labelIntegrantes = "Integrantes:";
  static const String labelIniciarSesion = "Iniciar sesión";
  static const String labelCrearCuenta = "Crear cuenta";
  static const String msgNameLastCarac = "Debe tener al menos 2 caracteres";
  static const String labelNombre = "Nombre";
  static const String labelApellido = "Apellido";
  static const String msgUserName = "Debe tener al menos 4 caracteres";
  static const String labelUserName = "Nombre de usuario";
  static const String msgPhone = "Debe tener al menos 6 números";
  static const String labelPhone = "Número de teléfono";
  static const String labelEmail = "Email";
  static const String msgEmail = "Debe ingresar un correo electrónico válido";
  static const String msgPassword = "La clave tener al menos de 8 caracteres";
  static const String labelClave = "Clave";
  static const String msgPassword2 = "La clave no coincide";
  static const String labelConfirmarClave = "Confirmar clave";
  static const String labelMostrarClave = "Mostrar clave";
  static const String labelQuesCuenta1 = "¿No tiene una cuenta?";
  static const String labelQuesCuenta2 = "Ya tiene cuenta?";
  static const String labelOpCuenta1 = "Cree una";
  static const String labelOpCuenta2 = "Inicie sesión";
  static const String labelGoogle = "Continuar con Google";
  static const String labelFacebook = "Continuar con Facebook";
}
